// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5nillLqZzbh81PSUyP2C0C3UAKulR_mc',
    appId: '1:771359961950:web:1c8e418409173e45dd55cf',
    messagingSenderId: '771359961950',
    projectId: 'mynotes-stefan',
    authDomain: 'mynotes-stefan.firebaseapp.com',
    storageBucket: 'mynotes-stefan.appspot.com',
    measurementId: 'G-LC9FXCVRP9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbl8MMcBOlCaxM3Fsssh1DNASyQJgmEac',
    appId: '1:771359961950:android:d55448a485c9ac0fdd55cf',
    messagingSenderId: '771359961950',
    projectId: 'mynotes-stefan',
    storageBucket: 'mynotes-stefan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxF9dtrH_hGJXoa0IDhiYzpfS1USIBg6E',
    appId: '1:771359961950:ios:925ae71a7eeb2f4cdd55cf',
    messagingSenderId: '771359961950',
    projectId: 'mynotes-stefan',
    storageBucket: 'mynotes-stefan.appspot.com',
    iosClientId: '771359961950-56uhlbrmnh7mk1rd4s2jp6kpk1q08kt4.apps.googleusercontent.com',
    iosBundleId: 'se.stefanhall.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxF9dtrH_hGJXoa0IDhiYzpfS1USIBg6E',
    appId: '1:771359961950:ios:925ae71a7eeb2f4cdd55cf',
    messagingSenderId: '771359961950',
    projectId: 'mynotes-stefan',
    storageBucket: 'mynotes-stefan.appspot.com',
    iosClientId: '771359961950-56uhlbrmnh7mk1rd4s2jp6kpk1q08kt4.apps.googleusercontent.com',
    iosBundleId: 'se.stefanhall.mynotes',
  );
}
